[package]
name = "lamu"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.13.0"
serde_json = "1.0.132"
tokio = "1.41.1"

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
strip = true
